package com.jrdevel.aboutus.core.model.lists;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import com.jrdevel.aboutus.core.model.PersonContacts;
import com.jrdevel.aboutus.core.model.lists.translate.ContactTypeTranslate;
import java.util.HashSet;
import java.util.Set;

/**
 * ContactType generated by hbm2java
 */
public class ContactType implements java.io.Serializable {

	private String id;
	private Set<ContactTypeTranslate> contactTypeTranslates = new HashSet<ContactTypeTranslate>(
			0);
	private Set<PersonContacts> personContactses = new HashSet<PersonContacts>(
			0);

	public ContactType() {
	}

	public ContactType(String id) {
		this.id = id;
	}

	public ContactType(String id,
			Set<ContactTypeTranslate> contactTypeTranslates,
			Set<PersonContacts> personContactses) {
		this.id = id;
		this.contactTypeTranslates = contactTypeTranslates;
		this.personContactses = personContactses;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Set<ContactTypeTranslate> getContactTypeTranslates() {
		return this.contactTypeTranslates;
	}

	public void setContactTypeTranslates(
			Set<ContactTypeTranslate> contactTypeTranslates) {
		this.contactTypeTranslates = contactTypeTranslates;
	}

	public Set<PersonContacts> getPersonContactses() {
		return this.personContactses;
	}

	public void setPersonContactses(Set<PersonContacts> personContactses) {
		this.personContactses = personContactses;
	}

}
