package com.jrdevel.aboutus.core.model.lists;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import com.jrdevel.aboutus.core.model.Event;
import com.jrdevel.aboutus.core.model.lists.translate.FrequencyTranslate;
import java.util.HashSet;
import java.util.Set;

/**
 * Frequency generated by hbm2java
 */
public class Frequency implements java.io.Serializable {

	private String id;
	private Set<FrequencyTranslate> frequencyTranslates = new HashSet<FrequencyTranslate>(
			0);
	private Set<Event> events = new HashSet<Event>(0);

	public Frequency() {
	}

	public Frequency(String id) {
		this.id = id;
	}

	public Frequency(String id, Set<FrequencyTranslate> frequencyTranslates,
			Set<Event> events) {
		this.id = id;
		this.frequencyTranslates = frequencyTranslates;
		this.events = events;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Set<FrequencyTranslate> getFrequencyTranslates() {
		return this.frequencyTranslates;
	}

	public void setFrequencyTranslates(
			Set<FrequencyTranslate> frequencyTranslates) {
		this.frequencyTranslates = frequencyTranslates;
	}

	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

}
