package com.jrdevel.aboutus.core.model.lists;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import com.jrdevel.aboutus.core.model.Person;
import com.jrdevel.aboutus.core.model.lists.translate.MemberTypeTranslate;
import java.util.HashSet;
import java.util.Set;

/**
 * MemberType generated by hbm2java
 */
public class MemberType implements java.io.Serializable {

	private String id;
	private Set<Person> persons = new HashSet<Person>(0);
	private Set<MemberTypeTranslate> memberTypeTranslates = new HashSet<MemberTypeTranslate>(
			0);

	public MemberType() {
	}

	public MemberType(String id) {
		this.id = id;
	}

	public MemberType(String id, Set<Person> persons,
			Set<MemberTypeTranslate> memberTypeTranslates) {
		this.id = id;
		this.persons = persons;
		this.memberTypeTranslates = memberTypeTranslates;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

	public Set<MemberTypeTranslate> getMemberTypeTranslates() {
		return this.memberTypeTranslates;
	}

	public void setMemberTypeTranslates(
			Set<MemberTypeTranslate> memberTypeTranslates) {
		this.memberTypeTranslates = memberTypeTranslates;
	}

}
