package com.jrdevel.aboutus.core.common.model.lists;

// Generated 2/jun/2014 21:02:16 by Hibernate Tools 3.4.0.CR1

import com.jrdevel.aboutus.core.common.model.Person;
import com.jrdevel.aboutus.core.common.model.lists.translate.CivilStatusTranslate;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CivilStatus generated by hbm2java
 */
@Entity
@Table(name = "lst_civilStatus")
public class CivilStatus implements java.io.Serializable {

	private String id;
	private Set<CivilStatusTranslate> civilStatusTranslates = new HashSet<CivilStatusTranslate>(
			0);
	private Set<Person> persons = new HashSet<Person>(0);

	public CivilStatus() {
	}

	public CivilStatus(String id) {
		this.id = id;
	}

	public CivilStatus(String id,
			Set<CivilStatusTranslate> civilStatusTranslates, Set<Person> persons) {
		this.id = id;
		this.civilStatusTranslates = civilStatusTranslates;
		this.persons = persons;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "civilStatus")
	public Set<CivilStatusTranslate> getCivilStatusTranslates() {
		return this.civilStatusTranslates;
	}

	public void setCivilStatusTranslates(
			Set<CivilStatusTranslate> civilStatusTranslates) {
		this.civilStatusTranslates = civilStatusTranslates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "civilStatus")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

}
