package com.jrdevel.aboutus.core.common.model;

// Generated 5/mai/2014 23:56:03 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name = "tbl_album")
public class Album implements java.io.Serializable {

	private Integer id;
	private Category category;
	private File file;
	private String title;
	private String description;
	private int position;
	private boolean published;
	private Date created;
	private Set<ItemAlbum> itemAlbums = new HashSet<ItemAlbum>(0);

	public Album() {
	}

	public Album(Category category, String title, String description,
			int position, boolean published) {
		this.category = category;
		this.title = title;
		this.description = description;
		this.position = position;
		this.published = published;
	}

	public Album(Category category, File file, String title,
			String description, int position, boolean published, Date created,
			Set<ItemAlbum> itemAlbums) {
		this.category = category;
		this.file = file;
		this.title = title;
		this.description = description;
		this.position = position;
		this.published = published;
		this.created = created;
		this.itemAlbums = itemAlbums;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoryId", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "thumb")
	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "position", nullable = false)
	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	@Column(name = "published", nullable = false)
	public boolean isPublished() {
		return this.published;
	}

	public void setPublished(boolean published) {
		this.published = published;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "album")
	public Set<ItemAlbum> getItemAlbums() {
		return this.itemAlbums;
	}

	public void setItemAlbums(Set<ItemAlbum> itemAlbums) {
		this.itemAlbums = itemAlbums;
	}

}
