package com.jrdevel.aboutus.core.common.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "tbl_customer")
public class Customer implements java.io.Serializable {

	private Integer id;
	private Plan plan;
	private String name;
	private String siteAlias;
	private Set<Video> videos = new HashSet<Video>(0);
	private Set<Article> articles = new HashSet<Article>(0);
	private Set<Event> events = new HashSet<Event>(0);
	private Set<Group> groups = new HashSet<Group>(0);
	private Set<Playlist> playlists = new HashSet<Playlist>(0);
	private Set<Person> persons = new HashSet<Person>(0);
	private Set<Folder> folders = new HashSet<Folder>(0);
	private Set<Music> musics = new HashSet<Music>(0);
	private Set<Audit> audits = new HashSet<Audit>(0);
	private Set<User> users = new HashSet<User>(0);
	private Set<File> files = new HashSet<File>(0);
	private Set<Banner> banners = new HashSet<Banner>(0);
	private Set<Church> churches = new HashSet<Church>(0);
	private Set<Category> categories = new HashSet<Category>(0);
	private Set<Album> albums = new HashSet<Album>(0);

	public Customer() {
	}

	public Customer(Plan plan, String name) {
		this.plan = plan;
		this.name = name;
	}

	public Customer(Plan plan, String name, String siteAlias,
			Set<Video> videos, Set<Article> articles, Set<Event> events,
			Set<Group> groups, Set<Playlist> playlists, Set<Person> persons,
			Set<Folder> folders, Set<Music> musics, Set<Audit> audits,
			Set<User> users, Set<File> files, Set<Banner> banners,
			Set<Church> churches, Set<Category> categories, Set<Album> albums) {
		this.plan = plan;
		this.name = name;
		this.siteAlias = siteAlias;
		this.videos = videos;
		this.articles = articles;
		this.events = events;
		this.groups = groups;
		this.playlists = playlists;
		this.persons = persons;
		this.folders = folders;
		this.musics = musics;
		this.audits = audits;
		this.users = users;
		this.files = files;
		this.banners = banners;
		this.churches = churches;
		this.categories = categories;
		this.albums = albums;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plan", nullable = false)
	public Plan getPlan() {
		return this.plan;
	}

	public void setPlan(Plan plan) {
		this.plan = plan;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "siteAlias")
	public String getSiteAlias() {
		return this.siteAlias;
	}

	public void setSiteAlias(String siteAlias) {
		this.siteAlias = siteAlias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Video> getVideos() {
		return this.videos;
	}

	public void setVideos(Set<Video> videos) {
		this.videos = videos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Group> getGroups() {
		return this.groups;
	}

	public void setGroups(Set<Group> groups) {
		this.groups = groups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Playlist> getPlaylists() {
		return this.playlists;
	}

	public void setPlaylists(Set<Playlist> playlists) {
		this.playlists = playlists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Folder> getFolders() {
		return this.folders;
	}

	public void setFolders(Set<Folder> folders) {
		this.folders = folders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Music> getMusics() {
		return this.musics;
	}

	public void setMusics(Set<Music> musics) {
		this.musics = musics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Audit> getAudits() {
		return this.audits;
	}

	public void setAudits(Set<Audit> audits) {
		this.audits = audits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<File> getFiles() {
		return this.files;
	}

	public void setFiles(Set<File> files) {
		this.files = files;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Banner> getBanners() {
		return this.banners;
	}

	public void setBanners(Set<Banner> banners) {
		this.banners = banners;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Church> getChurches() {
		return this.churches;
	}

	public void setChurches(Set<Church> churches) {
		this.churches = churches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Category> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Album> getAlbums() {
		return this.albums;
	}

	public void setAlbums(Set<Album> albums) {
		this.albums = albums;
	}

}
