package com.jrdevel.aboutus.core.common.model;

// Generated 29/mai/2014 18:48:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FolderRole generated by hbm2java
 */
@Entity
@Table(name = "tbl_folder_roles")
public class FolderRole implements java.io.Serializable {

	private Integer id;
	private User user;
	private Folder folder;
	private Group group;
	private boolean roleView;
	private boolean roleAdd;
	private boolean roleDownload;
	private boolean roleDelete;
	private boolean roleEdit;

	public FolderRole() {
	}

	public FolderRole(Folder folder, boolean roleView, boolean roleAdd,
			boolean roleDownload, boolean roleDelete, boolean roleEdit) {
		this.folder = folder;
		this.roleView = roleView;
		this.roleAdd = roleAdd;
		this.roleDownload = roleDownload;
		this.roleDelete = roleDelete;
		this.roleEdit = roleEdit;
	}

	public FolderRole(User user, Folder folder, Group group, boolean roleView,
			boolean roleAdd, boolean roleDownload, boolean roleDelete,
			boolean roleEdit) {
		this.user = user;
		this.folder = folder;
		this.group = group;
		this.roleView = roleView;
		this.roleAdd = roleAdd;
		this.roleDownload = roleDownload;
		this.roleDelete = roleDelete;
		this.roleEdit = roleEdit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "folder_id", nullable = false)
	public Folder getFolder() {
		return this.folder;
	}

	public void setFolder(Folder folder) {
		this.folder = folder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id")
	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	@Column(name = "roleView", nullable = false)
	public boolean isRoleView() {
		return this.roleView;
	}

	public void setRoleView(boolean roleView) {
		this.roleView = roleView;
	}

	@Column(name = "roleAdd", nullable = false)
	public boolean isRoleAdd() {
		return this.roleAdd;
	}

	public void setRoleAdd(boolean roleAdd) {
		this.roleAdd = roleAdd;
	}

	@Column(name = "roleDownload", nullable = false)
	public boolean isRoleDownload() {
		return this.roleDownload;
	}

	public void setRoleDownload(boolean roleDownload) {
		this.roleDownload = roleDownload;
	}

	@Column(name = "roleDelete", nullable = false)
	public boolean isRoleDelete() {
		return this.roleDelete;
	}

	public void setRoleDelete(boolean roleDelete) {
		this.roleDelete = roleDelete;
	}

	@Column(name = "roleEdit", nullable = false)
	public boolean isRoleEdit() {
		return this.roleEdit;
	}

	public void setRoleEdit(boolean roleEdit) {
		this.roleEdit = roleEdit;
	}

}
