package com.jrdevel.aboutus.core.common.model;

// Generated 29/Mar/2014 22:16:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Folder generated by hbm2java
 */
@Entity
@Table(name = "tbl_folder")
public class Folder implements java.io.Serializable {

	private Integer id;
	private Customer customer;
	private String name;
	private int parent;
	private boolean folderSys;
	private Set<File> files = new HashSet<File>(0);
	private Set<Music> musics = new HashSet<Music>(0);
	private Set<FolderRole> folderRoles = new HashSet<FolderRole>(0);

	public Folder() {
	}

	public Folder(Customer customer, String name, int parent, boolean folderSys) {
		this.customer = customer;
		this.name = name;
		this.parent = parent;
		this.folderSys = folderSys;
	}

	public Folder(Customer customer, String name, int parent,
			boolean folderSys, Set<File> files, Set<Music> musics,
			Set<FolderRole> folderRoles) {
		this.customer = customer;
		this.name = name;
		this.parent = parent;
		this.folderSys = folderSys;
		this.files = files;
		this.musics = musics;
		this.folderRoles = folderRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customerId", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "parent", nullable = false)
	public int getParent() {
		return this.parent;
	}

	public void setParent(int parent) {
		this.parent = parent;
	}

	@Column(name = "folderSys", nullable = false)
	public boolean isFolderSys() {
		return this.folderSys;
	}

	public void setFolderSys(boolean folderSys) {
		this.folderSys = folderSys;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "folder")
	public Set<File> getFiles() {
		return this.files;
	}

	public void setFiles(Set<File> files) {
		this.files = files;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "folder")
	public Set<Music> getMusics() {
		return this.musics;
	}

	public void setMusics(Set<Music> musics) {
		this.musics = musics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "folder")
	public Set<FolderRole> getFolderRoles() {
		return this.folderRoles;
	}

	public void setFolderRoles(Set<FolderRole> folderRoles) {
		this.folderRoles = folderRoles;
	}

}
