package com.jrdevel.aboutus.core.common.model;

// Generated 28/mai/2014 22:42:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MemberFunction generated by hbm2java
 */
@Entity
@Table(name = "tbl_memberFunctions")
public class MemberFunction implements java.io.Serializable {

	private Integer id;
	private Person person;
	private String function;

	public MemberFunction() {
	}

	public MemberFunction(Person person, String function) {
		this.person = person;
		this.function = function;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "person_id", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "function", nullable = false, length = 45)
	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

}
