package com.jrdevel.aboutus.core.common.model;

// Generated 2/jun/2014 21:02:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Session generated by hbm2java
 */
@Entity
@Table(name = "tbl_session")
public class Session implements java.io.Serializable {

	private String sessionId;
	private User user;
	private Date sessionRegister;
	private String userName;

	public Session() {
	}

	public Session(String sessionId, User user, Date sessionRegister,
			String userName) {
		this.sessionId = sessionId;
		this.user = user;
		this.sessionRegister = sessionRegister;
		this.userName = userName;
	}

	@Id
	@Column(name = "sessionId", unique = true, nullable = false, length = 200)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sessionRegister", nullable = false, length = 19)
	public Date getSessionRegister() {
		return this.sessionRegister;
	}

	public void setSessionRegister(Date sessionRegister) {
		this.sessionRegister = sessionRegister;
	}

	@Column(name = "userName", nullable = false)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
