package com.jrdevel.aboutus.core.common.model;

// Generated 1/jun/2014 19:22:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Video generated by hbm2java
 */
@Entity
@Table(name = "tbl_videos")
public class Video implements java.io.Serializable {

	private Integer id;
	private Category category;
	private File file;
	private String type;
	private String url;
	private String videoId;
	private boolean published;
	private String title;
	private String description;
	private int ordering;
	private Set<ItemAlbum> itemAlbums = new HashSet<ItemAlbum>(0);

	public Video() {
	}

	public Video(Category category, String url, boolean published,
			String title, int ordering) {
		this.category = category;
		this.url = url;
		this.published = published;
		this.title = title;
		this.ordering = ordering;
	}

	public Video(Category category, File file, String type, String url,
			String videoId, boolean published, String title,
			String description, int ordering, Set<ItemAlbum> itemAlbums) {
		this.category = category;
		this.file = file;
		this.type = type;
		this.url = url;
		this.videoId = videoId;
		this.published = published;
		this.title = title;
		this.description = description;
		this.ordering = ordering;
		this.itemAlbums = itemAlbums;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoryId", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "thumb")
	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	@Column(name = "type", length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "url", nullable = false, length = 65535)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "videoId")
	public String getVideoId() {
		return this.videoId;
	}

	public void setVideoId(String videoId) {
		this.videoId = videoId;
	}

	@Column(name = "published", nullable = false)
	public boolean isPublished() {
		return this.published;
	}

	public void setPublished(boolean published) {
		this.published = published;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ordering", nullable = false)
	public int getOrdering() {
		return this.ordering;
	}

	public void setOrdering(int ordering) {
		this.ordering = ordering;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "video")
	public Set<ItemAlbum> getItemAlbums() {
		return this.itemAlbums;
	}

	public void setItemAlbums(Set<ItemAlbum> itemAlbums) {
		this.itemAlbums = itemAlbums;
	}

}
