package com.jrdevel.aboutus.core.model.lists.translate;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import com.jrdevel.aboutus.core.model.lists.CivilStatus;

/**
 * CivilStatusTranslate generated by hbm2java
 */
public class CivilStatusTranslate implements java.io.Serializable {

	private Integer id;
	private CivilStatus civilStatus;
	private String langId;
	private String text;

	public CivilStatusTranslate() {
	}

	public CivilStatusTranslate(CivilStatus civilStatus, String langId,
			String text) {
		this.civilStatus = civilStatus;
		this.langId = langId;
		this.text = text;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CivilStatus getCivilStatus() {
		return this.civilStatus;
	}

	public void setCivilStatus(CivilStatus civilStatus) {
		this.civilStatus = civilStatus;
	}

	public String getLangId() {
		return this.langId;
	}

	public void setLangId(String langId) {
		this.langId = langId;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
