package com.jrdevel.aboutus.core.model.lists.translate;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import com.jrdevel.aboutus.core.model.lists.ContactType;

/**
 * ContactTypeTranslate generated by hbm2java
 */
public class ContactTypeTranslate implements java.io.Serializable {

	private Integer id;
	private ContactType contactType;
	private String langId;
	private String text;

	public ContactTypeTranslate() {
	}

	public ContactTypeTranslate(ContactType contactType, String langId,
			String text) {
		this.contactType = contactType;
		this.langId = langId;
		this.text = text;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ContactType getContactType() {
		return this.contactType;
	}

	public void setContactType(ContactType contactType) {
		this.contactType = contactType;
	}

	public String getLangId() {
		return this.langId;
	}

	public void setLangId(String langId) {
		this.langId = langId;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
