package com.jrdevel.aboutus.core.model.lists.translate;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import com.jrdevel.aboutus.core.model.lists.Frequency;

/**
 * FrequencyTranslate generated by hbm2java
 */
public class FrequencyTranslate implements java.io.Serializable {

	private Integer id;
	private Frequency frequency;
	private String langId;
	private String text;

	public FrequencyTranslate() {
	}

	public FrequencyTranslate(Frequency frequency, String langId, String text) {
		this.frequency = frequency;
		this.langId = langId;
		this.text = text;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Frequency getFrequency() {
		return this.frequency;
	}

	public void setFrequency(Frequency frequency) {
		this.frequency = frequency;
	}

	public String getLangId() {
		return this.langId;
	}

	public void setLangId(String langId) {
		this.langId = langId;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
