package com.jrdevel.aboutus.core.model.lists.translate;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import com.jrdevel.aboutus.core.model.lists.MemberType;

/**
 * MemberTypeTranslate generated by hbm2java
 */
public class MemberTypeTranslate implements java.io.Serializable {

	private Integer id;
	private MemberType memberType;
	private String langId;
	private String text;

	public MemberTypeTranslate() {
	}

	public MemberTypeTranslate(MemberType memberType, String langId, String text) {
		this.memberType = memberType;
		this.langId = langId;
		this.text = text;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MemberType getMemberType() {
		return this.memberType;
	}

	public void setMemberType(MemberType memberType) {
		this.memberType = memberType;
	}

	public String getLangId() {
		return this.langId;
	}

	public void setLangId(String langId) {
		this.langId = langId;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
