package com.jrdevel.aboutus.core.common.model.lists.translate;

// Generated 29/mai/2014 18:48:20 by Hibernate Tools 3.4.0.CR1

import com.jrdevel.aboutus.core.common.model.lists.CivilStatus;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CivilStatusTranslate generated by hbm2java
 */
@Entity
@Table(name = "trans_civilStatus")
public class CivilStatusTranslate implements java.io.Serializable {

	private Integer id;
	private CivilStatus civilStatus;
	private String langId;
	private String text;

	public CivilStatusTranslate() {
	}

	public CivilStatusTranslate(CivilStatus civilStatus, String langId,
			String text) {
		this.civilStatus = civilStatus;
		this.langId = langId;
		this.text = text;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lstId", nullable = false)
	public CivilStatus getCivilStatus() {
		return this.civilStatus;
	}

	public void setCivilStatus(CivilStatus civilStatus) {
		this.civilStatus = civilStatus;
	}

	@Column(name = "langId", nullable = false, length = 100)
	public String getLangId() {
		return this.langId;
	}

	public void setLangId(String langId) {
		this.langId = langId;
	}

	@Column(name = "text", nullable = false)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
