package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Album generated by hbm2java
 */
public class Album implements java.io.Serializable {

	private Integer id;
	private Category category;
	private File file;
	private String title;
	private String description;
	private int position;
	private boolean published;
	private Date created;
	private Set<ItemAlbum> itemAlbums = new HashSet<ItemAlbum>(0);

	public Album() {
	}

	public Album(Category category, String title, String description,
			int position, boolean published) {
		this.category = category;
		this.title = title;
		this.description = description;
		this.position = position;
		this.published = published;
	}

	public Album(Category category, File file, String title,
			String description, int position, boolean published, Date created,
			Set<ItemAlbum> itemAlbums) {
		this.category = category;
		this.file = file;
		this.title = title;
		this.description = description;
		this.position = position;
		this.published = published;
		this.created = created;
		this.itemAlbums = itemAlbums;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	public boolean isPublished() {
		return this.published;
	}

	public void setPublished(boolean published) {
		this.published = published;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Set<ItemAlbum> getItemAlbums() {
		return this.itemAlbums;
	}

	public void setItemAlbums(Set<ItemAlbum> itemAlbums) {
		this.itemAlbums = itemAlbums;
	}

}
