package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Article generated by hbm2java
 */
public class Article implements java.io.Serializable {

	private Integer id;
	private Category category;
	private File file;
	private String introarticle;
	private String article;
	private String title;
	private Date created;
	private Date publishUp;
	private Date publishDown;
	private int ordering;
	private int hits;
	private boolean homepage;
	private String author;

	public Article() {
	}

	public Article(Category category, String article, String title,
			Date created, Date publishUp, int ordering, int hits,
			boolean homepage) {
		this.category = category;
		this.article = article;
		this.title = title;
		this.created = created;
		this.publishUp = publishUp;
		this.ordering = ordering;
		this.hits = hits;
		this.homepage = homepage;
	}

	public Article(Category category, File file, String introarticle,
			String article, String title, Date created, Date publishUp,
			Date publishDown, int ordering, int hits, boolean homepage,
			String author) {
		this.category = category;
		this.file = file;
		this.introarticle = introarticle;
		this.article = article;
		this.title = title;
		this.created = created;
		this.publishUp = publishUp;
		this.publishDown = publishDown;
		this.ordering = ordering;
		this.hits = hits;
		this.homepage = homepage;
		this.author = author;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	public String getIntroarticle() {
		return this.introarticle;
	}

	public void setIntroarticle(String introarticle) {
		this.introarticle = introarticle;
	}

	public String getArticle() {
		return this.article;
	}

	public void setArticle(String article) {
		this.article = article;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getPublishUp() {
		return this.publishUp;
	}

	public void setPublishUp(Date publishUp) {
		this.publishUp = publishUp;
	}

	public Date getPublishDown() {
		return this.publishDown;
	}

	public void setPublishDown(Date publishDown) {
		this.publishDown = publishDown;
	}

	public int getOrdering() {
		return this.ordering;
	}

	public void setOrdering(int ordering) {
		this.ordering = ordering;
	}

	public int getHits() {
		return this.hits;
	}

	public void setHits(int hits) {
		this.hits = hits;
	}

	public boolean isHomepage() {
		return this.homepage;
	}

	public void setHomepage(boolean homepage) {
		this.homepage = homepage;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

}
