package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Audit generated by hbm2java
 */
public class Audit implements java.io.Serializable {

	private Integer id;
	private int userId;
	private int actionId;
	private Date actionDate;
	private String tableName;
	private int tableId;
	private String collumnName;
	private String collumnValue;
	private String collumnNewValue;
	private String objectName;
	private String objectTitle;
	private String userName;

	public Audit() {
	}

	public Audit(int userId, int actionId, Date actionDate, String tableName,
			int tableId) {
		this.userId = userId;
		this.actionId = actionId;
		this.actionDate = actionDate;
		this.tableName = tableName;
		this.tableId = tableId;
	}

	public Audit(int userId, int actionId, Date actionDate, String tableName,
			int tableId, String collumnName, String collumnValue,
			String collumnNewValue, String objectName, String objectTitle,
			String userName) {
		this.userId = userId;
		this.actionId = actionId;
		this.actionDate = actionDate;
		this.tableName = tableName;
		this.tableId = tableId;
		this.collumnName = collumnName;
		this.collumnValue = collumnValue;
		this.collumnNewValue = collumnNewValue;
		this.objectName = objectName;
		this.objectTitle = objectTitle;
		this.userName = userName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getActionId() {
		return this.actionId;
	}

	public void setActionId(int actionId) {
		this.actionId = actionId;
	}

	public Date getActionDate() {
		return this.actionDate;
	}

	public void setActionDate(Date actionDate) {
		this.actionDate = actionDate;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public int getTableId() {
		return this.tableId;
	}

	public void setTableId(int tableId) {
		this.tableId = tableId;
	}

	public String getCollumnName() {
		return this.collumnName;
	}

	public void setCollumnName(String collumnName) {
		this.collumnName = collumnName;
	}

	public String getCollumnValue() {
		return this.collumnValue;
	}

	public void setCollumnValue(String collumnValue) {
		this.collumnValue = collumnValue;
	}

	public String getCollumnNewValue() {
		return this.collumnNewValue;
	}

	public void setCollumnNewValue(String collumnNewValue) {
		this.collumnNewValue = collumnNewValue;
	}

	public String getObjectName() {
		return this.objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	public String getObjectTitle() {
		return this.objectTitle;
	}

	public void setObjectTitle(String objectTitle) {
		this.objectTitle = objectTitle;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
