package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Banner generated by hbm2java
 */
public class Banner implements java.io.Serializable {

	private Integer id;
	private File file;
	private String name;
	private String alias;
	private String link;
	private Date publishUp;
	private Date publishDown;
	private int ordering;

	public Banner() {
	}

	public Banner(String name, Date publishUp, int ordering) {
		this.name = name;
		this.publishUp = publishUp;
		this.ordering = ordering;
	}

	public Banner(File file, String name, String alias, String link,
			Date publishUp, Date publishDown, int ordering) {
		this.file = file;
		this.name = name;
		this.alias = alias;
		this.link = link;
		this.publishUp = publishUp;
		this.publishDown = publishDown;
		this.ordering = ordering;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public Date getPublishUp() {
		return this.publishUp;
	}

	public void setPublishUp(Date publishUp) {
		this.publishUp = publishUp;
	}

	public Date getPublishDown() {
		return this.publishDown;
	}

	public void setPublishDown(Date publishDown) {
		this.publishDown = publishDown;
	}

	public int getOrdering() {
		return this.ordering;
	}

	public void setOrdering(int ordering) {
		this.ordering = ordering;
	}

}
