package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Batch generated by hbm2java
 */
public class Batch implements java.io.Serializable {

	private Integer id;
	private Date dateStart;
	private Date dateEnd;
	private int quantityProcessed;
	private String finalStatus;
	private String notes;

	public Batch() {
	}

	public Batch(Date dateStart, Date dateEnd, int quantityProcessed,
			String finalStatus) {
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.quantityProcessed = quantityProcessed;
		this.finalStatus = finalStatus;
	}

	public Batch(Date dateStart, Date dateEnd, int quantityProcessed,
			String finalStatus, String notes) {
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.quantityProcessed = quantityProcessed;
		this.finalStatus = finalStatus;
		this.notes = notes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDateStart() {
		return this.dateStart;
	}

	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}

	public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

	public int getQuantityProcessed() {
		return this.quantityProcessed;
	}

	public void setQuantityProcessed(int quantityProcessed) {
		this.quantityProcessed = quantityProcessed;
	}

	public String getFinalStatus() {
		return this.finalStatus;
	}

	public void setFinalStatus(String finalStatus) {
		this.finalStatus = finalStatus;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
