package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import com.jrdevel.aboutus.core.model.lists.Country;
import java.util.HashSet;
import java.util.Set;

/**
 * Church generated by hbm2java
 */
public class Church implements java.io.Serializable {

	private Integer id;
	private Country country;
	private File file;
	private Customer customer;
	private String name;
	private String completeName;
	private String address;
	private String state;
	private String postalCode;
	private Integer nif;
	private Set<Person> persons = new HashSet<Person>(0);
	private Set<User> users = new HashSet<User>(0);

	public Church() {
	}

	public Church(Customer customer, String name, String completeName) {
		this.customer = customer;
		this.name = name;
		this.completeName = completeName;
	}

	public Church(Country country, File file, Customer customer, String name,
			String completeName, String address, String state,
			String postalCode, Integer nif, Set<Person> persons, Set<User> users) {
		this.country = country;
		this.file = file;
		this.customer = customer;
		this.name = name;
		this.completeName = completeName;
		this.address = address;
		this.state = state;
		this.postalCode = postalCode;
		this.nif = nif;
		this.persons = persons;
		this.users = users;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCompleteName() {
		return this.completeName;
	}

	public void setCompleteName(String completeName) {
		this.completeName = completeName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public Integer getNif() {
		return this.nif;
	}

	public void setNif(Integer nif) {
		this.nif = nif;
	}

	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
