package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

/**
 * EventRecurrence generated by hbm2java
 */
public class EventRecurrence implements java.io.Serializable {

	private Integer id;
	private Event event;
	private Integer day;
	private Integer week;
	private Integer month;

	public EventRecurrence() {
	}

	public EventRecurrence(Event event) {
		this.event = event;
	}

	public EventRecurrence(Event event, Integer day, Integer week, Integer month) {
		this.event = event;
		this.day = day;
		this.week = week;
		this.month = month;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Integer getDay() {
		return this.day;
	}

	public void setDay(Integer day) {
		this.day = day;
	}

	public Integer getWeek() {
		return this.week;
	}

	public void setWeek(Integer week) {
		this.week = week;
	}

	public Integer getMonth() {
		return this.month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

}
