package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import com.jrdevel.aboutus.core.model.lists.Frequency;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event implements java.io.Serializable {

	private Integer id;
	private Frequency frequency;
	private Category category;
	private File file;
	private String what;
	private Date startsOn;
	private Date endsOn;
	private Date startsAt;
	private Date endsAt;
	private int separation;
	private Integer count;
	private Date until;
	private String description;
	private String location;
	private String style;
	private boolean published;
	private Set<EventRecurrence> eventRecurrences = new HashSet<EventRecurrence>(
			0);

	public Event() {
	}

	public Event(String what, int separation, boolean published) {
		this.what = what;
		this.separation = separation;
		this.published = published;
	}

	public Event(Frequency frequency, Category category, File file,
			String what, Date startsOn, Date endsOn, Date startsAt,
			Date endsAt, int separation, Integer count, Date until,
			String description, String location, String style,
			boolean published, Set<EventRecurrence> eventRecurrences) {
		this.frequency = frequency;
		this.category = category;
		this.file = file;
		this.what = what;
		this.startsOn = startsOn;
		this.endsOn = endsOn;
		this.startsAt = startsAt;
		this.endsAt = endsAt;
		this.separation = separation;
		this.count = count;
		this.until = until;
		this.description = description;
		this.location = location;
		this.style = style;
		this.published = published;
		this.eventRecurrences = eventRecurrences;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Frequency getFrequency() {
		return this.frequency;
	}

	public void setFrequency(Frequency frequency) {
		this.frequency = frequency;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	public String getWhat() {
		return this.what;
	}

	public void setWhat(String what) {
		this.what = what;
	}

	public Date getStartsOn() {
		return this.startsOn;
	}

	public void setStartsOn(Date startsOn) {
		this.startsOn = startsOn;
	}

	public Date getEndsOn() {
		return this.endsOn;
	}

	public void setEndsOn(Date endsOn) {
		this.endsOn = endsOn;
	}

	public Date getStartsAt() {
		return this.startsAt;
	}

	public void setStartsAt(Date startsAt) {
		this.startsAt = startsAt;
	}

	public Date getEndsAt() {
		return this.endsAt;
	}

	public void setEndsAt(Date endsAt) {
		this.endsAt = endsAt;
	}

	public int getSeparation() {
		return this.separation;
	}

	public void setSeparation(int separation) {
		this.separation = separation;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Date getUntil() {
		return this.until;
	}

	public void setUntil(Date until) {
		this.until = until;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getStyle() {
		return this.style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	public boolean isPublished() {
		return this.published;
	}

	public void setPublished(boolean published) {
		this.published = published;
	}

	public Set<EventRecurrence> getEventRecurrences() {
		return this.eventRecurrences;
	}

	public void setEventRecurrences(Set<EventRecurrence> eventRecurrences) {
		this.eventRecurrences = eventRecurrences;
	}

}
