package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

/**
 * FileData generated by hbm2java
 */
public class FileData implements java.io.Serializable {

	private Integer id;
	private File file;
	private byte[] data;
	private Integer dataType;

	public FileData() {
	}

	public FileData(File file) {
		this.file = file;
	}

	public FileData(File file, byte[] data, Integer dataType) {
		this.file = file;
		this.data = data;
		this.dataType = dataType;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	public byte[] getData() {
		return this.data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

	public Integer getDataType() {
		return this.dataType;
	}

	public void setDataType(Integer dataType) {
		this.dataType = dataType;
	}

}
