package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Folder generated by hbm2java
 */
public class Folder implements java.io.Serializable {

	private Integer id;
	private String name;
	private int parent;
	private boolean folderSys;
	private Set<File> files = new HashSet<File>(0);
	private Set<Music> musics = new HashSet<Music>(0);
	private Set<FolderRole> folderRoles = new HashSet<FolderRole>(0);

	public Folder() {
	}

	public Folder(String name, int parent, boolean folderSys) {
		this.name = name;
		this.parent = parent;
		this.folderSys = folderSys;
	}

	public Folder(String name, int parent, boolean folderSys, Set<File> files,
			Set<Music> musics, Set<FolderRole> folderRoles) {
		this.name = name;
		this.parent = parent;
		this.folderSys = folderSys;
		this.files = files;
		this.musics = musics;
		this.folderRoles = folderRoles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getParent() {
		return this.parent;
	}

	public void setParent(int parent) {
		this.parent = parent;
	}

	public boolean isFolderSys() {
		return this.folderSys;
	}

	public void setFolderSys(boolean folderSys) {
		this.folderSys = folderSys;
	}

	public Set<File> getFiles() {
		return this.files;
	}

	public void setFiles(Set<File> files) {
		this.files = files;
	}

	public Set<Music> getMusics() {
		return this.musics;
	}

	public void setMusics(Set<Music> musics) {
		this.musics = musics;
	}

	public Set<FolderRole> getFolderRoles() {
		return this.folderRoles;
	}

	public void setFolderRoles(Set<FolderRole> folderRoles) {
		this.folderRoles = folderRoles;
	}

}
