package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

/**
 * FolderRole generated by hbm2java
 */
public class FolderRole implements java.io.Serializable {

	private Integer id;
	private User user;
	private Group group;
	private Folder folder;
	private boolean roleView;
	private boolean roleAdd;
	private boolean roleDownload;
	private boolean roleDelete;
	private boolean roleEdit;

	public FolderRole() {
	}

	public FolderRole(Folder folder, boolean roleView, boolean roleAdd,
			boolean roleDownload, boolean roleDelete, boolean roleEdit) {
		this.folder = folder;
		this.roleView = roleView;
		this.roleAdd = roleAdd;
		this.roleDownload = roleDownload;
		this.roleDelete = roleDelete;
		this.roleEdit = roleEdit;
	}

	public FolderRole(User user, Group group, Folder folder, boolean roleView,
			boolean roleAdd, boolean roleDownload, boolean roleDelete,
			boolean roleEdit) {
		this.user = user;
		this.group = group;
		this.folder = folder;
		this.roleView = roleView;
		this.roleAdd = roleAdd;
		this.roleDownload = roleDownload;
		this.roleDelete = roleDelete;
		this.roleEdit = roleEdit;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	public Folder getFolder() {
		return this.folder;
	}

	public void setFolder(Folder folder) {
		this.folder = folder;
	}

	public boolean isRoleView() {
		return this.roleView;
	}

	public void setRoleView(boolean roleView) {
		this.roleView = roleView;
	}

	public boolean isRoleAdd() {
		return this.roleAdd;
	}

	public void setRoleAdd(boolean roleAdd) {
		this.roleAdd = roleAdd;
	}

	public boolean isRoleDownload() {
		return this.roleDownload;
	}

	public void setRoleDownload(boolean roleDownload) {
		this.roleDownload = roleDownload;
	}

	public boolean isRoleDelete() {
		return this.roleDelete;
	}

	public void setRoleDelete(boolean roleDelete) {
		this.roleDelete = roleDelete;
	}

	public boolean isRoleEdit() {
		return this.roleEdit;
	}

	public void setRoleEdit(boolean roleEdit) {
		this.roleEdit = roleEdit;
	}

}
