package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Instrument generated by hbm2java
 */
public class Instrument implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Tab> tabs = new HashSet<Tab>(0);

	public Instrument() {
	}

	public Instrument(String name) {
		this.name = name;
	}

	public Instrument(String name, Set<Tab> tabs) {
		this.name = name;
		this.tabs = tabs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Tab> getTabs() {
		return this.tabs;
	}

	public void setTabs(Set<Tab> tabs) {
		this.tabs = tabs;
	}

}
