package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

/**
 * ItemAlbum generated by hbm2java
 */
public class ItemAlbum implements java.io.Serializable {

	private Integer id;
	private Album album;
	private Video video;
	private File file;
	private String title;
	private String description;
	private int position;

	public ItemAlbum() {
	}

	public ItemAlbum(Album album, int position) {
		this.album = album;
		this.position = position;
	}

	public ItemAlbum(Album album, Video video, File file, String title,
			String description, int position) {
		this.album = album;
		this.video = video;
		this.file = file;
		this.title = title;
		this.description = description;
		this.position = position;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Album getAlbum() {
		return this.album;
	}

	public void setAlbum(Album album) {
		this.album = album;
	}

	public Video getVideo() {
		return this.video;
	}

	public void setVideo(Video video) {
		this.video = video;
	}

	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

}
