package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

/**
 * MemberFunction generated by hbm2java
 */
public class MemberFunction implements java.io.Serializable {

	private Integer id;
	private Person person;
	private String function;

	public MemberFunction() {
	}

	public MemberFunction(Person person, String function) {
		this.person = person;
		this.function = function;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

}
