package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Music generated by hbm2java
 */
public class Music implements java.io.Serializable {

	private Integer id;
	private Integer version;
	private Folder folder;
	private String title;
	private String liryc;
	private String seq;
	private String drumsStyle;
	private Integer time;
	private String originalTone;
	private String observations;
	private String link;
	private Date createDate;
	private Date modificationDate;
	private String author;
	private String musicNotes;
	private boolean favorite;
	private Set<Tab> tabs = new HashSet<Tab>(0);
	private Set<Playlist> playlists = new HashSet<Playlist>(0);

	public Music() {
	}

	public Music(String title, String liryc, Date createDate, boolean favorite) {
		this.title = title;
		this.liryc = liryc;
		this.createDate = createDate;
		this.favorite = favorite;
	}

	public Music(Folder folder, String title, String liryc, String seq,
			String drumsStyle, Integer time, String originalTone,
			String observations, String link, Date createDate,
			Date modificationDate, String author, String musicNotes,
			boolean favorite, Set<Tab> tabs, Set<Playlist> playlists) {
		this.folder = folder;
		this.title = title;
		this.liryc = liryc;
		this.seq = seq;
		this.drumsStyle = drumsStyle;
		this.time = time;
		this.originalTone = originalTone;
		this.observations = observations;
		this.link = link;
		this.createDate = createDate;
		this.modificationDate = modificationDate;
		this.author = author;
		this.musicNotes = musicNotes;
		this.favorite = favorite;
		this.tabs = tabs;
		this.playlists = playlists;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Folder getFolder() {
		return this.folder;
	}

	public void setFolder(Folder folder) {
		this.folder = folder;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getLiryc() {
		return this.liryc;
	}

	public void setLiryc(String liryc) {
		this.liryc = liryc;
	}

	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	public String getDrumsStyle() {
		return this.drumsStyle;
	}

	public void setDrumsStyle(String drumsStyle) {
		this.drumsStyle = drumsStyle;
	}

	public Integer getTime() {
		return this.time;
	}

	public void setTime(Integer time) {
		this.time = time;
	}

	public String getOriginalTone() {
		return this.originalTone;
	}

	public void setOriginalTone(String originalTone) {
		this.originalTone = originalTone;
	}

	public String getObservations() {
		return this.observations;
	}

	public void setObservations(String observations) {
		this.observations = observations;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModificationDate() {
		return this.modificationDate;
	}

	public void setModificationDate(Date modificationDate) {
		this.modificationDate = modificationDate;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getMusicNotes() {
		return this.musicNotes;
	}

	public void setMusicNotes(String musicNotes) {
		this.musicNotes = musicNotes;
	}

	public boolean isFavorite() {
		return this.favorite;
	}

	public void setFavorite(boolean favorite) {
		this.favorite = favorite;
	}

	public Set<Tab> getTabs() {
		return this.tabs;
	}

	public void setTabs(Set<Tab> tabs) {
		this.tabs = tabs;
	}

	public Set<Playlist> getPlaylists() {
		return this.playlists;
	}

	public void setPlaylists(Set<Playlist> playlists) {
		this.playlists = playlists;
	}

}
