package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import com.jrdevel.aboutus.core.model.lists.ContactType;

/**
 * PersonContacts generated by hbm2java
 */
public class PersonContacts implements java.io.Serializable {

	private Integer id;
	private ContactType contactType;
	private Person person;
	private String value;

	public PersonContacts() {
	}

	public PersonContacts(ContactType contactType, Person person) {
		this.contactType = contactType;
		this.person = person;
	}

	public PersonContacts(ContactType contactType, Person person, String value) {
		this.contactType = contactType;
		this.person = person;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ContactType getContactType() {
		return this.contactType;
	}

	public void setContactType(ContactType contactType) {
		this.contactType = contactType;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
