package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Plan generated by hbm2java
 */
public class Plan implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Customer> customers = new HashSet<Customer>(0);

	public Plan() {
	}

	public Plan(String name) {
		this.name = name;
	}

	public Plan(String name, Set<Customer> customers) {
		this.name = name;
		this.customers = customers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}
