package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Playlist generated by hbm2java
 */
public class Playlist implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date createDate;
	private Date modificationDate;
	private Set<Music> musics = new HashSet<Music>(0);

	public Playlist() {
	}

	public Playlist(String name, Date createDate, Date modificationDate) {
		this.name = name;
		this.createDate = createDate;
		this.modificationDate = modificationDate;
	}

	public Playlist(String name, Date createDate, Date modificationDate,
			Set<Music> musics) {
		this.name = name;
		this.createDate = createDate;
		this.modificationDate = modificationDate;
		this.musics = musics;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModificationDate() {
		return this.modificationDate;
	}

	public void setModificationDate(Date modificationDate) {
		this.modificationDate = modificationDate;
	}

	public Set<Music> getMusics() {
		return this.musics;
	}

	public void setMusics(Set<Music> musics) {
		this.musics = musics;
	}

}
