package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Session generated by hbm2java
 */
public class Session implements java.io.Serializable {

	private String sessionId;
	private User user;
	private Date sessionRegister;
	private String userName;

	public Session() {
	}

	public Session(String sessionId, User user, Date sessionRegister,
			String userName) {
		this.sessionId = sessionId;
		this.user = user;
		this.sessionRegister = sessionRegister;
		this.userName = userName;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getSessionRegister() {
		return this.sessionRegister;
	}

	public void setSessionRegister(Date sessionRegister) {
		this.sessionRegister = sessionRegister;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
