package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

/**
 * Tab generated by hbm2java
 */
public class Tab implements java.io.Serializable {

	private Integer id;
	private Music music;
	private Instrument instrument;
	private byte[] content;

	public Tab() {
	}

	public Tab(Music music, Instrument instrument, byte[] content) {
		this.music = music;
		this.instrument = instrument;
		this.content = content;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Music getMusic() {
		return this.music;
	}

	public void setMusic(Music music) {
		this.music = music;
	}

	public Instrument getInstrument() {
		return this.instrument;
	}

	public void setInstrument(Instrument instrument) {
		this.instrument = instrument;
	}

	public byte[] getContent() {
		return this.content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}

}
