package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

/**
 * TblGroupTblPermissionId generated by hbm2java
 */
public class TblGroupTblPermissionId implements java.io.Serializable {

	private int permissionsId;
	private int tblGroupId;

	public TblGroupTblPermissionId() {
	}

	public TblGroupTblPermissionId(int permissionsId, int tblGroupId) {
		this.permissionsId = permissionsId;
		this.tblGroupId = tblGroupId;
	}

	public int getPermissionsId() {
		return this.permissionsId;
	}

	public void setPermissionsId(int permissionsId) {
		this.permissionsId = permissionsId;
	}

	public int getTblGroupId() {
		return this.tblGroupId;
	}

	public void setTblGroupId(int tblGroupId) {
		this.tblGroupId = tblGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblGroupTblPermissionId))
			return false;
		TblGroupTblPermissionId castOther = (TblGroupTblPermissionId) other;

		return (this.getPermissionsId() == castOther.getPermissionsId())
				&& (this.getTblGroupId() == castOther.getTblGroupId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPermissionsId();
		result = 37 * result + this.getTblGroupId();
		return result;
	}

}
