package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

/**
 * TblGroupTblPermission generated by hbm2java
 */
public class TblGroupTblPermission implements java.io.Serializable {

	private TblGroupTblPermissionId id;

	public TblGroupTblPermission() {
	}

	public TblGroupTblPermission(TblGroupTblPermissionId id) {
		this.id = id;
	}

	public TblGroupTblPermissionId getId() {
		return this.id;
	}

	public void setId(TblGroupTblPermissionId id) {
		this.id = id;
	}

}
