package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

/**
 * TblPermissionTblGroup generated by hbm2java
 */
public class TblPermissionTblGroup implements java.io.Serializable {

	private TblPermissionTblGroupId id;

	public TblPermissionTblGroup() {
	}

	public TblPermissionTblGroup(TblPermissionTblGroupId id) {
		this.id = id;
	}

	public TblPermissionTblGroupId getId() {
		return this.id;
	}

	public void setId(TblPermissionTblGroupId id) {
		this.id = id;
	}

}
