package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

/**
 * TblPermissionTblGroupId generated by hbm2java
 */
public class TblPermissionTblGroupId implements java.io.Serializable {

	private int groupsId;
	private int tblPermissionId;

	public TblPermissionTblGroupId() {
	}

	public TblPermissionTblGroupId(int groupsId, int tblPermissionId) {
		this.groupsId = groupsId;
		this.tblPermissionId = tblPermissionId;
	}

	public int getGroupsId() {
		return this.groupsId;
	}

	public void setGroupsId(int groupsId) {
		this.groupsId = groupsId;
	}

	public int getTblPermissionId() {
		return this.tblPermissionId;
	}

	public void setTblPermissionId(int tblPermissionId) {
		this.tblPermissionId = tblPermissionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblPermissionTblGroupId))
			return false;
		TblPermissionTblGroupId castOther = (TblPermissionTblGroupId) other;

		return (this.getGroupsId() == castOther.getGroupsId())
				&& (this.getTblPermissionId() == castOther.getTblPermissionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGroupsId();
		result = 37 * result + this.getTblPermissionId();
		return result;
	}

}
