package com.jrdevel.aboutus.core.model;

// Generated 10/Mar/2014 22:16:04 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblPermissionTblGroup generated by hbm2java
 */
@Entity
@Table(name = "tbl_permission_tbl_group")
public class TblPermissionTblGroup implements java.io.Serializable {

	private TblPermissionTblGroupId id;

	public TblPermissionTblGroup() {
	}

	public TblPermissionTblGroup(TblPermissionTblGroupId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "groupsId", column = @Column(name = "groups_id", nullable = false)),
			@AttributeOverride(name = "tblPermissionId", column = @Column(name = "tbl_permission_id", nullable = false)) })
	public TblPermissionTblGroupId getId() {
		return this.id;
	}

	public void setId(TblPermissionTblGroupId id) {
		this.id = id;
	}

}
