package com.jrdevel.aboutus.core.model;

// Generated 10/Mar/2014 22:16:04 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblPermissionTblGroupId generated by hbm2java
 */
@Embeddable
public class TblPermissionTblGroupId implements java.io.Serializable {

	private int groupsId;
	private int tblPermissionId;

	public TblPermissionTblGroupId() {
	}

	public TblPermissionTblGroupId(int groupsId, int tblPermissionId) {
		this.groupsId = groupsId;
		this.tblPermissionId = tblPermissionId;
	}

	@Column(name = "groups_id", nullable = false)
	public int getGroupsId() {
		return this.groupsId;
	}

	public void setGroupsId(int groupsId) {
		this.groupsId = groupsId;
	}

	@Column(name = "tbl_permission_id", nullable = false)
	public int getTblPermissionId() {
		return this.tblPermissionId;
	}

	public void setTblPermissionId(int tblPermissionId) {
		this.tblPermissionId = tblPermissionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblPermissionTblGroupId))
			return false;
		TblPermissionTblGroupId castOther = (TblPermissionTblGroupId) other;

		return (this.getGroupsId() == castOther.getGroupsId())
				&& (this.getTblPermissionId() == castOther.getTblPermissionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGroupsId();
		result = 37 * result + this.getTblPermissionId();
		return result;
	}

}
