package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private Church church;
	private Person person;
	private Customer customer;
	private String email;
	private String password;
	private boolean block;
	private boolean activation;
	private Date registerDate;
	private Date lastvisitDate;
	private Set<Register> registers = new HashSet<Register>(0);
	private Set<Permission> permissions = new HashSet<Permission>(0);
	private Set<Session> sessions = new HashSet<Session>(0);
	private Set<FolderRole> folderRoles = new HashSet<FolderRole>(0);
	private Set<Group> groups = new HashSet<Group>(0);

	public User() {
	}

	public User(String email, String password, boolean block,
			boolean activation, Date registerDate) {
		this.email = email;
		this.password = password;
		this.block = block;
		this.activation = activation;
		this.registerDate = registerDate;
	}

	public User(Church church, Person person, Customer customer, String email,
			String password, boolean block, boolean activation,
			Date registerDate, Date lastvisitDate, Set<Register> registers,
			Set<Permission> permissions, Set<Session> sessions,
			Set<FolderRole> folderRoles, Set<Group> groups) {
		this.church = church;
		this.person = person;
		this.customer = customer;
		this.email = email;
		this.password = password;
		this.block = block;
		this.activation = activation;
		this.registerDate = registerDate;
		this.lastvisitDate = lastvisitDate;
		this.registers = registers;
		this.permissions = permissions;
		this.sessions = sessions;
		this.folderRoles = folderRoles;
		this.groups = groups;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Church getChurch() {
		return this.church;
	}

	public void setChurch(Church church) {
		this.church = church;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isBlock() {
		return this.block;
	}

	public void setBlock(boolean block) {
		this.block = block;
	}

	public boolean isActivation() {
		return this.activation;
	}

	public void setActivation(boolean activation) {
		this.activation = activation;
	}

	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	public Date getLastvisitDate() {
		return this.lastvisitDate;
	}

	public void setLastvisitDate(Date lastvisitDate) {
		this.lastvisitDate = lastvisitDate;
	}

	public Set<Register> getRegisters() {
		return this.registers;
	}

	public void setRegisters(Set<Register> registers) {
		this.registers = registers;
	}

	public Set<Permission> getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Set<Permission> permissions) {
		this.permissions = permissions;
	}

	public Set<Session> getSessions() {
		return this.sessions;
	}

	public void setSessions(Set<Session> sessions) {
		this.sessions = sessions;
	}

	public Set<FolderRole> getFolderRoles() {
		return this.folderRoles;
	}

	public void setFolderRoles(Set<FolderRole> folderRoles) {
		this.folderRoles = folderRoles;
	}

	public Set<Group> getGroups() {
		return this.groups;
	}

	public void setGroups(Set<Group> groups) {
		this.groups = groups;
	}

}
