package com.jrdevel.aboutus.core.model;

// Generated 9/Mar/2014 21:10:27 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Video generated by hbm2java
 */
public class Video implements java.io.Serializable {

	private Integer id;
	private Category category;
	private File file;
	private String type;
	private String url;
	private String videoId;
	private boolean published;
	private String title;
	private String description;
	private int ordering;
	private Set<ItemAlbum> itemAlbums = new HashSet<ItemAlbum>(0);

	public Video() {
	}

	public Video(Category category, String url, boolean published,
			String title, int ordering) {
		this.category = category;
		this.url = url;
		this.published = published;
		this.title = title;
		this.ordering = ordering;
	}

	public Video(Category category, File file, String type, String url,
			String videoId, boolean published, String title,
			String description, int ordering, Set<ItemAlbum> itemAlbums) {
		this.category = category;
		this.file = file;
		this.type = type;
		this.url = url;
		this.videoId = videoId;
		this.published = published;
		this.title = title;
		this.description = description;
		this.ordering = ordering;
		this.itemAlbums = itemAlbums;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getVideoId() {
		return this.videoId;
	}

	public void setVideoId(String videoId) {
		this.videoId = videoId;
	}

	public boolean isPublished() {
		return this.published;
	}

	public void setPublished(boolean published) {
		this.published = published;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getOrdering() {
		return this.ordering;
	}

	public void setOrdering(int ordering) {
		this.ordering = ordering;
	}

	public Set<ItemAlbum> getItemAlbums() {
		return this.itemAlbums;
	}

	public void setItemAlbums(Set<ItemAlbum> itemAlbums) {
		this.itemAlbums = itemAlbums;
	}

}
